version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      

# version: '3.1'
# services:
#   app:
#     container_name: springboot
#     image: springboot
#     build: ./
#     ports:
#       - "8080:8080"
#     depends_on:
#       - dbpostgresql
#     network:
#       - spring_net
#   dbpostgresql:
#     image: postgres
#     ports:
#       - "5432:5432"
#     network:
#       - spring_net
#     environment:
#      POSTGRES_USERNAME: postgres
#      POSTGRES_PASSWORD: password
# networks:
#   spring_net: {}      